### ISSUE TITLE
VPA updater pod crashing with "invalid memory address or nil pointer dereference."

### ISSUE THREAD

**Issue by phyllisstein** [kubernetes/autoscaler#1258]
👋 Hey folks! Just wanted to flag an issue I'm seeing with the VPA updater pod. It seems to crash every five minutes or so with the following error message:

```
I0919 04:43:55.060264       9 flags.go:52] FLAG: --alsologtostderr="false"
I0919 04:43:55.060515       9 flags.go:52] FLAG: --eviction-tolerance="0.5"
I0919 04:43:55.060526       9 flags.go:52] FLAG: --httptest.serve=""
I0919 04:43:55.060530       9 flags.go:52] FLAG: --log-backtrace-at=":0"
I0919 04:43:55.060535       9 flags.go:52] FLAG: --log-dir=""
I0919 04:43:55.060540       9 flags.go:52] FLAG: --logtostderr="false"
I0919 04:43:55.060543       9 flags.go:52] FLAG: --min-replicas="2"
I0919 04:43:55.060546       9 flags.go:52] FLAG: --stderrthreshold="0"
I0919 04:43:55.060550       9 flags.go:52] FLAG: --updater-interval="1m0s"
I0919 04:43:55.060553       9 flags.go:52] FLAG: --v="4"
I0919 04:43:55.060556       9 flags.go:52] FLAG: --vmodule=""
I0919 04:43:55.060561       9 main.go:45] Vertical Pod Autoscaler 0.2.0 Updater
I0919 04:43:55.061818       9 reflector.go:202] Starting reflector *v1alpha1.VerticalPodAutoscaler (1h0m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/api.go:83
I0919 04:43:55.061847       9 reflector.go:240] Listing and watching *v1alpha1.VerticalPodAutoscaler from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/utils/vpa/api.go:83
I0919 04:43:55.161615       9 shared_informer.go:123] caches populated
I0919 04:43:55.161638       9 api.go:87] Initial VPA synced successfully
I0919 04:43:55.161733       9 reflector.go:202] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:155
I0919 04:43:55.161758       9 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:155
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe572b3]
 goroutine 1 [running]:
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/priority.(*UpdatePriorityCalculator).getUpdatePriority(0xc42077fb00, 0xc4203d66a0, 0xc4208416e0, 0xc4203d66a0, 0xc4208416e0, 0x0)
	/usr/local/google/home/bskiba/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go:121 +0x7b3
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/priority.(*UpdatePriorityCalculator).AddPod(0xc42077fb00, 0xc4203d66a0, 0xc42040db40, 0xbee092f1cd7ad123, 0xe0271a439, 0x17bb6e0)
	/usr/local/google/home/bskiba/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/priority/update_priority_calculator.go:75 +0x1b3
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic.(*updater).getPodsForUpdate(0xc4202001c0, 0xc420862710, 0x2, 0x2, 0xc42031ab40, 0xc420862710, 0x2, 0x2)
	/usr/local/google/home/bskiba/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:123 +0x1d9
k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic.(*updater).RunOnce(0xc4202001c0)
	/usr/local/google/home/bskiba/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/logic/updater.go:102 +0xa3f
main.main()
	/usr/local/google/home/bskiba/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/updater/main.go:55 +0x16e
```

Is there a stable Git commit that it makes sense to roll back to while this is being looked at? Thanks in advance for your help, and thanks for all your work on the autoscaler.

**Comment by bskiba** [comment]
This is fixed in the master branch. We should probably patch.

**Comment by phyllisstein** [comment]
Thanks for the heads up! I'll try reinstalling from `master` and see how it goes.

**Comment by bskiba** [comment]
@phyllisstein Is the issue fixed for you?

**Comment by johanneswuerbach** [comment]
I had the same issue with the released images, but building from master resolved it 👍

**Comment by bskiba** [comment]
cool, thanks, I'll close then. Feel free to reopen if needed.

/close

**Comment by phyllisstein** [comment]
Yup, apologies for not following up, but building the images from `master` did the trick on my end as well. Thanks for pointing me in the right direction!

**Comment by bskiba** [comment]
No problem, glad this worked out for you!

**Comment by johanneswuerbach** [comment]
@bskiba any idea when a new release is cut including this fix?

**Comment by bskiba** [comment]
Will try to release a new version inside the next to weeks
