### ISSUE TITLE
Crash when Autoscaler starts and AutoscalinGroups have 0 instances

### ISSUE THREAD

**Issue by gtie** [kubernetes/autoscaler#1411]
We are using Cluster Autoscaler (CA) to right-size several AutoScalingGroups in AWS (each featuring different AZ/taint combination). When the leader encouters such an autoscaling group, it crashes with SIGSEGV (and then, next leader does the same, and so on).

Here is the traceback:
```
I1116 18:30:35.877019       1 request.go:485] Throttling request took 90.934181ms, request: GET:https://100.64.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
I1116 18:30:36.077059       1 request.go:485] Throttling request took 196.99294ms, request: PUT:https://100.64.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x134867f]

goroutine 119 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).buildNodeFromTemplate(0xc421932bd0, 0xc42359f6c0, 0xc422d9a7c0, 0x0, 0x0, 0xc4206fe750)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:243 +0x3df
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsNodeGroup).TemplateNodeInfo(0xc4208737e0, 0xc421784e70, 0xc423623c00, 0x40)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:303 +0x68
k8s.io/autoscaler/cluster-autoscaler/core.GetNodeInfosForGroups(0xc421b52b00, 0xa, 0x10, 0x3b71440, 0xc4235f9c10, 0x3b932e0, 0xc420372000, 0xc422578940, 0x5, 0x8, ...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/utils.go:258 +0x296
k8s.io/autoscaler/cluster-autoscaler/core.ScaleUp(0xc4212bcb40, 0xc421023500, 0xc42376a280, 0xc42286b200, 0x1f, 0x20, 0xc421b52b00, 0xa, 0x10, 0xc422578940, ...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:253 +0x3ef
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc4235cd720, 0xbef3e112c492bf84, 0x28bfbca95, 0x5c8ef20, 0x0, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:281 +0x1df4
main.run(0xc4209bc870)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:291 +0x4c8
main.main.func2(0xc4201ac360)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:372 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:155 +0x92
```

Above happens with version 1.3.1 and 1.12.1.

**Comment by seh** [comment]
I just had the same thing happen here, with this arrangement: six autoscaling groups, grouped by two different instance types into three subnets, each in a different availability zone.

| ASG | Instance type | Subnet |
| --- | ------------- | ------ |
| a-0 | p2.xlarge     | az-1-a |
| a-1 | p2.xlarge     | az-1-b |
| a-2 | p2.xlarge     | az-1-c |
| b-0 | g3s.xlarge    | az-1-a |
| b-1 | g3s.xlarge    | az-1-b |
| b-2 | g3s.xlarge    | az-1-c |

**Comment by seh** [comment]
I see the same failure in version _1.13.0-alpha.1_.

Ah, I see the problem: [`(*cloudprovider/aws/AwsManager).getAsgTemplate` returns an `asgTemplate` instance with a null value in its "InstanceType" field](https://sourcegraph.com/github.com/kubernetes/autoscaler@master/-/blob/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L202) when the given instance type is unknown, with no entry in [the `InstanceTypes` map](https://sourcegraph.com/github.com/kubernetes/autoscaler@master/-/blob/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L29-1014). In this case, that unknown instance type is "g3s.xlarge."

That `getAsgTemplate` method should confirm that the given instance type is known, and return an error if not. The method already [allows returning a second value of type `error`](https://sourcegraph.com/github.com/kubernetes/autoscaler@master/-/blob/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L184).

**Comment by seh** [comment]
Note that [the JSON file fetched](https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.json) by the _gen.go_ file does have entries for instance type "g3s.xlarge."

**Comment by seh** [comment]
We haven't updated the set of known instance types since 28 October 2017, by @sethpollack's hand (ea9aa6fe1479b3fb1e51a7df093e5a1d7d13bea8).

**Comment by seh** [comment]
@gtie, which instance type were you trying to use?

**Comment by sethpollack** [comment]
@seh If you want to update the instance types you can just run https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/Makefile#L47 and then create a PR.

**Comment by gtie** [comment]
@seh , in my case the ASGs with 0 instances were of the C5(9xl) and R5(12xl) instance types. I see that those are missing as well: 
https://github.com/kubernetes/autoscaler/issues/1387

**Comment by seh** [comment]
#1422 supplies the missing instance types. I'd also like to elaborate the error handling here, which I'll tackle in a separate patch.
