### ISSUE TITLE
autodiscovery with several tags does not work

### ISSUE THREAD

**Issue by lwolf** [kubernetes/autoscaler#176]
I'm trying to setup autoscaler for 2 clusters in a single aws zone like described [here](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#auto-discovery-setup):
having any single tag out of two works fine (`k8s.io/cluster-autoscaler/enabled` or `kubernetes.io/cluster/production`)
but as soon as I set 2 tags container starts to crush
```
- --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/production
```

```
I0714 12:48:42.177681       1 status.go:122] Succesfully wrote status configmap with body "Cluster-autoscaler status at 2017-07-14 12:48:41.487387224 +0000 UTC:
Initializing"
I0714 12:48:42.177952       1 auto_scaling.go:96] Starting getAutoscalingGroupsByTag with key=k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/production
F0714 12:48:42.397512       1 cloud_provider_builder.go:91] Failed to create AWS cloud provider: Failed to get ASGs: Unable to find ASGs for tag key k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/production
goroutine 54 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.stacks(0xc4201c8400, 0xc42086a480, 0xd8, 0x101)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).output(0x2d8c7e0, 0xc400000003, 0xc4206a6370, 0x2cda4be, 0x19, 0x5b, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:717 +0x348
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.(*loggingT).printf(0x2d8c7e0, 0x3, 0x1f0319e, 0x27, 0xc4205bd220, 0x1, 0x1)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog.Fatalf(0x1f0319e, 0x27, 0xc4205bd220, 0x1, 0x1)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder.CloudProviderBuilder.Build(0x7fff3c1589d0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fff3c158a2d, 0x4a, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go:91 +0x68d
k8s.io/autoscaler/cluster-autoscaler/core.NewAutoscalingContext(0xa, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0x0, 0x7fff3c158a2d, 0x4a, 0xd18c2e2800, 0x1ed7132, 0xa, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaling_context.go:115 +0x13d
k8s.io/autoscaler/cluster-autoscaler/core.NewStaticAutoscaler(0xa, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0x0, 0x7fff3c158a2d, 0x4a, 0xd18c2e2800, 0x1ed7132, 0xa, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:54 +0x113
k8s.io/autoscaler/cluster-autoscaler/core.(*AutoscalerBuilderImpl).Build(0xc4203366c0, 0x410db8, 0x120)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/dynamic_autoscaler.go:131 +0x10e
k8s.io/autoscaler/cluster-autoscaler/core.NewPollingAutoscaler(0x2d10c80, 0xc4203366c0, 0x1ce0860)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/polling_autoscaler.go:36 +0x35
k8s.io/autoscaler/cluster-autoscaler/core.NewAutoscaler(0xa, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0x0, 0x7fff3c158a2d, 0x4a, 0xd18c2e2800, 0x1ed7132, 0xa, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:59 +0x5c6
main.run(0xc4202f2320)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:184 +0x253
main.main.func2(0xc4202e6060)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:276 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97
```

clusters deployed using kube-aws
Cluster Autoscaler version 0.5.4

**Comment by mwielgus** [comment]
cc: @mumoshu

Please try CA 0.6. There were some issues around autodiscovery in 0.5.4.

**Comment by mumoshu** [comment]
@lwolf Hi, a kube-aws maintainer here!

Probably you're using kube-aws v0.9.7 final which uses a forked version of CA 0.5.4 built by me, and yes, as @mwielgus it had several issues and more importantly, it doesn't support passing multiple tags concatenated with comma like `k8s.io/cluster-autoscaler/enabled,kubernetes.io/cluster/production` yet.

Modifying sub-settings of `clusterAutoscalerImage` to use CA 0.6.0 would fix it. Otherwise, you can just wait for kube-aws v0.9.8-rc.1 which uses CA 0.6 by default.

**Comment by lwolf** [comment]
Thanks for the help, will try newer version
