### ISSUE TITLE
cluster-autoscaler 1.2.2 panics on scale-up with zero size ASGs on AWS

### ISSUE THREAD

**Issue by deweysasser** [kubernetes/autoscaler#1845]
# Summary
cluster-autoscaler 1.2.2, when a scale-up event triggers and an ASG in the set has min_size=0 and desired_size=0 panics

# Details

## Configuration

* Kubernetes running via EKS in AWS us-east-2
* [kube2iam](https://github.com/jtblin/kube2iam) in use for role assignments
* all instance types involved are t3.2xlarge
* 3 nodes exist in a different ASG with a taint to keep the workload described here away

## Procedure

* configure 2 ASGs, one of which has 0 for desired and min size:
* configure a deployment which applies memory pressure to the system
* scale the deployment to cause an autoscaling event
* cluster-autoscaler panics with:

```
I0329 19:25:36.083152       1 static_autoscaler.go:114] Starting main loop
I0329 19:25:36.224835       1 static_autoscaler.go:263] Filtering out schedulables
I0329 19:25:36.225488       1 static_autoscaler.go:273] No schedulable pods
I0329 19:25:36.225521       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-wshzk is unschedulable
I0329 19:25:36.225527       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-kspsd is unschedulable
I0329 19:25:36.225531       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-8qm5k is unschedulable
I0329 19:25:36.225535       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-6msrv is unschedulable
I0329 19:25:36.225539       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-wz54m is unschedulable
I0329 19:25:36.225543       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-2v72b is unschedulable
I0329 19:25:36.225547       1 scale_up.go:59] Pod default/memory-load-6d466bcd85-fbspb is unschedulable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x145dccd]

goroutine 63 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).buildNodeFromTemplate(0xc420736320, 0xc4211d0030, 0xc42190d1c0, 0xc42190d1c0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:407 +0x48d
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*Asg).TemplateNodeInfo(0xc4211d0030, 0xc420efab40, 0xc421882f90, 0x2d)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:294 +0x78
k8s.io/autoscaler/cluster-autoscaler/core.GetNodeInfosForGroups(0xc42159d4e0, 0x4, 0x4, 0x5a07ca0, 0xc42168b180, 0x5a14620, 0xc420d42000, 0xc4210ceaa0, 0x3, 0x4, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/utils.go:228 +0x65a
k8s.io/autoscaler/cluster-autoscaler/core.ScaleUp(0xc421286fc0, 0xc4218ad8c0, 0x7, 0x8, 0xc42159d4e0, 0x4, 0x4, 0xc4210ceaa0, 0x3, 0x4, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:63 +0x393
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc420627a80, 0xed4306830, 0xe04f47b72, 0x5bf5180, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:299 +0x296a
main.run(0xc4206fac80)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:269 +0x474
main.main.func2(0xc42005fbc0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:356 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:145 +0x97
```
## Procedure Details

Initial ASG configuration:

<img width="821" alt="Screen Shot 2019-03-29 at 3 25 12 PM" src="https://user-images.githubusercontent.com/1293125/55258560-918c1100-5239-11e9-9565-83f8bfa941b8.png">

cluster autoscale definition:
```
...
     containers:
        - image: k8s.gcr.io/cluster-autoscaler:v1.2.2
          name: cluster-autoscaler
          env:
            - name: AWS_REGION
              value: us-east-2
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --expander=least-waste
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/sandbox-main
...
```

Memory pressure deployment created with "kubectl create":

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: memory-load
  name: memory-load
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/memory-load
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: memory-load
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: memory-load
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: memory-load
        resources:
          requests:
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

# Work Around

## Avoidance

Ensure that all ASGs have a minimum of 1 node and it works as expected, both scale-up and scale-down.  This will prevent the issue from occurring or recover from it if it has already occurred.

**Comment by Jeffwan** [comment]
@deweysasser Thanks reporting this issue. Have you tried CA v1.2.5? Since you use v1.2.2, I assume you still use EKS v1.10 cluster?  I recently setup similar env with kubernetes v1.11 and CA v1.3.8. But I  didn't put large load and have not meet this issue. I can help look at this issue if it can always be reproduced.
