### ISSUE TITLE
Support for AWS r5ad. instances

### ISSUE THREAD

**Issue by casidiablo** [kubernetes/autoscaler#1936]
They are just like `r5a.` instances, but use NVMe SSD instead of EBS.

Right now the autoscaler is crashing because of lack of support for them:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1406f8f]

goroutine 49 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).buildNodeFromTemplate(0xc420adeb00, 0xc420f2b440, 0xc42341bb40, 0x0, 0x0, 0xc420f7d110)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:241 +0x3df
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsNodeGroup).TemplateNodeInfo(0xc4212cdcf0, 0xc420db5020, 0xc421b21e30, 0x61)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:308 +0x68
k8s.io/autoscaler/cluster-autoscaler/core.GetNodeInfosForGroups(0xc4221b7600, 0x40, 0x40, 0xc420db5020, 0x4137d60, 0xc420cdfb90, 0x415a8a0, 0xc4201bd000, 0xc4234c22c0, 0x8, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/utils.go:286 +0x443
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc420f2b950, 0xbf27363d55b28006, 0x2766d29a2, 0x64687c0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:138 +0x36a
main.run(0xc42043c0a0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:302 +0x1dd
main.main.func2(0x4118ce0, 0xc4207c4300)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:381 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:155 +0xee
```

The error message could also be improved

**Comment by Jeffwan** [comment]
What CA version are you using? @casidiablo Looks like r5a. family has been added to list.

**Comment by casidiablo** [comment]
Yes, the `r5a` family is the list. This request is for the `r5ad` family.

**Comment by Jeffwan** [comment]
@casidiablo I can regenerate instance list, which CA version are your running?

**Comment by casidiablo** [comment]
Sorry for the delay. We are running 1.11

**Comment by Jeffwan** [comment]
https://github.com/kubernetes/autoscaler/pull/1970 Sorry for late response. @casidiablo 
I would suggest you to upgrade to v1.12.  I will cherry-pick back to 1.11-1.14 later But seems community doesn't release v1.11 upgrade anymore. I can help confirm that. If we determine not to maintain 1.11. Please use corresponding version for v1.12

**Comment by casidiablo** [comment]
Sure, that's something we are planning to do soon anyways. Thanks a lot
