### ISSUE TITLE
cluster-autoscaler v1.15.5 does not support  AWS IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by canhnt** [kubernetes/autoscaler#2951]
The latest `cluster-autoscaler` image supporting k8s-v1.15.x is [v1.15.5](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.5). It uses the `aws-sdk-go v1.16.26`

https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.15.5/cluster-autoscaler/go.mod#L13

According to https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/, in order to make app compatible with IAM Roles for Service Accounts (IRSA), the aws-sdk-go library must be `1.23.13` or later.

Because of this, when running `k8s.gcr.io/cluster-autoscaler:v1.15.5` as a deployment with a service  account binding to a IRSA role, the pod crashes with following error:
```
E0320 15:19:32.164423       1 aws_manager.go:259] Failed to regenerate ASG cache: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::xxxx:assumed-role/mycluster-nonprod120200320110003227800000007/i-04a1cdf82bd6532b8 is not authorized to perform: autoscaling:DescribeTags
        status code: 403, request id: 64a60b2b-94bc-4fbb-99cc-138f756ae503
F0320 15:19:32.164785       1 aws_cloud_provider.go:351] Failed to create AWS Manager: cannot autodiscover ASGs: AccessDenied: User: arn:aws:sts::xxx:assumed-role/mycluster-nonprod120200320110003227800000007/i-04a1cdf82bd6532b8 is not authorized to perform: autoscaling:DescribeTags
        status code: 403, request id: 64a60b2b-94bc-4fbb-99cc-138f756ae503
goroutine 54 [running]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.stacks(0x4cbb001, 0x3, 0xc00104e380, 0x163)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:900 +0xb1
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.(*loggingT).output(0x4cbb040, 0xc000000003, 0xc0002fe230, 0x4c2e7ef, 0x15, 0x15f, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:815 +0xe6
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.(*loggingT).printf(0x4cbb040, 0x3, 0x2b8d072, 0x20, 0xc00075ab28, 0x1, 0x1)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:727 +0x14e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog.Fatalf(...)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/klog.go:1309
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.BuildAWS(0xa, 0x3fe8000000000000, 0x3fe0000000000000, 0x45d964b800, 0x1176592e000, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, ...)
...
```

It always tried to use NodeGroup role rather than IRSA role.

Other versions do not have above issues: 
- `k8s.gcr.io/cluster-autoscaler:v1.14.6`
- `k8s.gcr.io/cluster-autoscaler:v1.17.1`

**Comment by Jeffwan** [comment]
https://github.com/kubernetes/autoscaler/issues/2920

Let's track in this issue.

**Comment by canhnt** [comment]
Close as duplicated with #2920
