### ISSUE TITLE
Autoscaling on packet fails to create nodes in version 1.0.2

### ISSUE THREAD

**Issue by knrt10** [kubernetes/autoscaler#3461]
### Steps to reproduce

- Run a Kubernetes cluster on [Lokomotive](github.com/kinvolk/lokomotive)
- Apply [cluster-autoscaler component](https://github.com/kinvolk/lokomotive/pull/859)
- Create an Nginx deployment with a resource request of 32Gb or anything else.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: "Exists"
          effect: NoSchedule
      containers:
      - image: nginxinc/nginx-unprivileged:1.15.12
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Gi"
```

### Expected

It should autoscale and create nodes on Packet.

### Actual

It panics and crashes the pod 

<details><summary>Successul POST request sent to packet</summary>
<p>

```console
I0826 12:06:49.366153       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-n4gxs is unschedulable
I0826 12:06:49.366160       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-wbpkw is unschedulable
I0826 12:06:49.366165       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-mjv58 is unschedulable
I0826 12:06:49.366170       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-r9j6x is unschedulable
I0826 12:06:49.366175       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-xszwg is unschedulable
I0826 12:06:49.366180       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-87bzg is unschedulable
I0826 12:06:49.366185       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-w72dw is unschedulable
I0826 12:06:49.366192       1 scale_up.go:322] Pod testing/nginx-9f6766bc5-5lmpv is unschedulable
I0826 12:06:49.366219       1 scale_up.go:360] Upcoming 0 nodes
I0826 12:06:49.367239       1 scale_up.go:452] Best option to resize: pool-1
I0826 12:06:49.367253       1 scale_up.go:456] Estimated 8 nodes needed in pool-1
I0826 12:06:49.367265       1 balancing_processor.go:111] Requested scale-up (8) exceeds node group set capacity, capping to 4
I0826 12:06:49.367277       1 scale_up.go:569] Final scale-up plan: [{pool-1 0->4 (max: 4)}]
I0826 12:06:49.367293       1 scale_up.go:658] Scale-up: setting group pool-1 size to 4
I0826 12:06:49.367434       1 event.go:278] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cluster-autoscaler-status", UID:"18e5e711-87e1-4ef9-bbaa-a5b4a54a753a", APIVersion:"v1", ResourceVersion:"41005", FieldPath:""}): type: 'Normal' reason: 'ScaledUpGroup' Scale-up: setting group pool-1 size to 4
I0826 12:06:50.697567       1 packet_manager_rest.go:194] response Status: 200 OK
I0826 12:06:51.007443       1 packet_manager_rest.go:217] Nodegroup pool-1: 0/10
I0826 12:06:51.007464       1 packet_node_group.go:88] Increasing size by 4, 0->4
I0826 12:06:51.007469       1 packet_manager_rest.go:301] Updating node count to 4 for nodegroup pool-1
I0826 12:06:51.007779       1 packet_manager_rest.go:319] Creating new node
I0826 12:06:51.007794       1 packet_manager_rest.go:320] POST https://api.packet.net/projects/0361e5d1-8d07-44af-8ad0-f88c8c0578a2/devices
```
</details>

<details><summary>Failed logs and code panics</summary>
<p>

```console
E0826 12:06:53.131268       1 packet_manager_rest.go:281] Failed to create device using Packet API: &{503 Service Unavailable 503 HTTP/2.0 2 0 map[Cache-Control:[no-cache] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[5c8d6dd8ce151e91-AMS] Cf-Request-Id:[04cc42fb7d00001e91fe312200000001] Content-Length:[97] Content-Type:[application/json; charset=utf-8] Date:[Wed, 26 Aug 2020 12:06:53 GMT] Expect-Ct:[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"] Server:[cloudflare] Set-Cookie:[__cfduid=dcd538863b4212483abe6957e48271e0f1598443611; expires=Fri, 25-Sep-20 12:06:51 GMT; path=/; domain=.packet.net; HttpOnly; SameSite=Lax; Secure] Vary:[Origin] X-Request-Id:[37e27740-b5cf-488a-97fa-2388cf046e73]] {0xc000148640} 97 [] false false map[] 0xc0013dc500 0xc000f30bb0}
panic: (*http.Response) (0x2f80720,0xc000ec70e0)

goroutine 127 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/packet.(*packetManagerRest).createNode(0xc0010e40c0, 0xc000fe4000, 0x591d, 0x7ffd4226e8f5, 0x6)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go:282 +0xcbc
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/packet.(*packetManagerRest).createNodes(0xc0010e40c0, 0x7ffd4226e8f5, 0x6, 0x4, 0xc001252c30, 0x3)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/packet/packet_manager_rest.go:309 +0x1c4
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/packet.(*packetNodeGroup).IncreaseSize(0xc000ec6120, 0x4, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/packet/packet_node_group.go:91 +0x2c8
k8s.io/autoscaler/cluster-autoscaler/core.executeScaleUp(0xc000267400, 0xc0010e29a0, 0x3984540, 0xc000ec6120, 0x0, 0x4, 0x4, 0x0, 0x0, 0xbfc9b1f655d2fd45, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:662 +0x218
k8s.io/autoscaler/cluster-autoscaler/core.ScaleUp(0xc000267400, 0xc000aaee00, 0xc0010e29a0, 0xc000d06880, 0x8, 0x8, 0xc0011bf780, 0x2, 0x2, 0xc000d0c360, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:571 +0x164e
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc000723f40, 0xbfc9b1f6559b0fb7, 0x2a80cc3ca, 0x54c8460, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:405 +0x2b4a
main.run(0xc0009d7540)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:344 +0x293
main.main.func2(0x391e3e0, 0xc0009506c0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:423 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:207 +0x132
```

**Comment by rawkode** [comment]
Hi @knrt10,

That 503 looks like it is potentially a transient error, could you confirm if this is still a problem?

**Comment by knrt10** [comment]
Thank you for your reply @rawkode. Yes, I just checked, it still occurs

**Comment by invidian** [comment]
@rawkode the actual error is:
```
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 503
< date: Wed, 26 Aug 2020 13:47:29 GMT
< content-type: application/json; charset=utf-8
< content-length: 97
< set-cookie: __cfduid=d4f89349c81716fd7faa081a6bb3324441598449646; expires=Fri, 25-Sep-20 13:47:26 GMT; path=/; domain=.packet.net; HttpOnly; SameSite=Lax; Secure
< cache-control: no-cache
< vary: Origin
< x-request-id: 423fec93-8c0b-4d23-b9f8-6382a385ed43
< cf-cache-status: DYNAMIC
< cf-request-id: 04cc9f13a6000027a0e11f6200000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 5c8e0132aedc27a0-PRG
<
* Connection #0 to host api.packet.net left intact
{"errors":["The facility ams1 has no provisionable c3.small.x86 servers matching your criteria"]}
```

The point here is: cluster-autoscaler panics when a request returns error, that seems wrong.

The other issue is selecting node type to provision, which seems to be incorrect as well, though I'm not sure if this is not the configuration issue on Lokomotive side.

**Comment by detiber** [comment]
I started taking a swing at this in https://github.com/kubernetes/autoscaler/pull/3483/files, but went down a bit of a rabbit hole cleaning up some other bits along the way. Will attempt to revisit it and pull apart some of the changes over the next few days.
