### ISSUE TITLE
Odd memory issue with cluster-autoscaler.

### ISSUE THREAD

**Issue by moos3** [kubernetes/autoscaler#358]
I'm trying to get the autoscaler working with a cluster that was created with KOPS. I'm seeing this error when the pod comes up.

```I0920 20:37:26.489510       1 reflector.go:236] Listing and watching *v1.ReplicationController from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.489846       1 reflector.go:198] Starting reflector *v1beta1.ReplicaSet (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.489903       1 reflector.go:236] Listing and watching *v1beta1.ReplicaSet from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.490205       1 reflector.go:198] Starting reflector *v1beta1.StatefulSet (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.490259       1 reflector.go:236] Listing and watching *v1beta1.StatefulSet from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.490452       1 reflector.go:236] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:144
I0920 20:37:26.490655       1 reflector.go:236] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:169
I0920 20:37:26.490747       1 reflector.go:236] Listing and watching *v1.Service from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.490946       1 reflector.go:236] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:207
I0920 20:37:26.491113       1 reflector.go:236] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:237
I0920 20:37:26.491289       1 reflector.go:236] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:259
I0920 20:37:26.491654       1 reflector.go:198] Starting reflector *v1.PersistentVolumeClaim (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.491712       1 reflector.go:236] Listing and watching *v1.PersistentVolumeClaim from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.492011       1 reflector.go:198] Starting reflector *v1.PersistentVolume (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.492075       1 reflector.go:236] Listing and watching *v1.PersistentVolume from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72
I0920 20:37:26.688727       1 request.go:638] Throttling request took 196.449667ms, request: GET:https://100.64.0.1:443/api/v1/persistentvolumes?resourceVersion=0
I0920 20:37:26.896315       1 request.go:638] Throttling request took 97.840641ms, request: PUT:https://100.64.0.1:443/api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
I0920 20:37:26.988531       1 main.go:162] Registered cleanup signal handler
I0920 20:37:28.410225       1 leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
I0920 20:37:30.420620       1 leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
I0920 20:37:32.595659       1 leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
I0920 20:37:34.689220       1 leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
I0920 20:37:36.700092       1 leaderelection.go:204] successfully renewed lease kube-system/cluster-autoscaler
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x208794a]
 goroutine 45 [running]:
k8s.io/autoscaler/cluster-autoscaler/core.(*PollingAutoscaler).Poll(0xc420885180, 0x4, 0xed154c890)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/polling_autoscaler.go:95 +0x9a
k8s.io/autoscaler/cluster-autoscaler/core.(*PollingAutoscaler).RunOnce(0xc420885180, 0xed154c890, 0xe3aeeac2c, 0x39bb020, 0x39bb020, 0x7ffe9508661e)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/polling_autoscaler.go:68 +0x76
main.run(0xc420367bd0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:201 +0x4d8
main.main.func2(0xc42061e060)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:279 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97```

**Comment by mwielgus** [comment]
What ClusterAutoscaler/Kubernetes version do you have?

cc: @mumoshu

**Comment by moos3** [comment]
Ca 0.6.2
Kube 1.7.5

**Comment by moos3** [comment]
any updates on this? This happens on 0.6.0, 0.6.1 and 0.6.2.

**Comment by MaciekPytel** [comment]
@moos3 PollingAutoscaler (the logic behing `--node-group-auto-discovery` flag), which seems to be the source of the issue, is maintained by @mumoshu. Not sure how busy he is right now. 

In the meantime you can consider using static ASG configuration (using `--nodes` instead of `--node-group-auto-discovery`) as a workaround.

**Comment by moos3** [comment]
So this error happens when you dont set a cloud provider.
