### ISSUE TITLE
Cluster autoscaler crashing with AWS self managed nodes and node group autodiscovery

### ISSUE THREAD

**Issue by danthegoodman1** [kubernetes/autoscaler#3891]
**Which component are you using?**: Cluster Autoscaler

**What version of the component are you using?**: 1.20.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ v1.18.9-eks-d1db3c
</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**:

Cluster autoscaler will identify self managed node groups that have appropriate tagging.

**What happened instead?**:

It crashes

**How to reproduce it (as minimally and precisely as possible)**:

Here is the following section of the CA that changes it crashing vs working:

```yaml
command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --expander=least-waste
            # - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/dantestingcluster
            - --nodes=1:20:gggggg-NodeGroup1-1KVYZBBPT7CIT
            - --nodes=1:20:gggggg-NodeGroup2-16KZFF54VE5IZ
            - --nodes=1:20:gggggg-NodeGroup3-1N3XO1S6HIKGA
            - --max-node-provision-time=5m0s
```
This configuration works, it is when I comment out the `- --nodes=...` lines and uncomment the `- --node-group-auto-discovery=...` line it crashes.

It also prints out lots of duplicates of the following:

```go
goroutine 255 [chan receive]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc000129e30, 0xc001226cc0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/shared_informer.go:628 +0x53
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x2e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc001232a50, 0xc001258440)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62

goroutine 256 [chan receive]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*controller).Run.func1(0xc000c71ce0, 0xc0006c17a0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/controller.go:130 +0x34
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*controller).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/controller.go:129 +0xa4

goroutine 273 [select]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc000bbcfc0, 0xc0040c65dfbdd2a2, 0x4778bce17, 0x61696a0, 0x4178580, 0xc0009b6440, 0xc001439bc8, 0xc001235d40, 0xc000c71ce0, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:463 +0x1a1
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc000bbcfc0, 0xc000c71ce0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:427 +0x663
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:221 +0x38
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a78ef0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001439ef0, 0x416c0a0, 0xc000bb4aa0, 0x1, 0xc000c71ce0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000bbcfc0, 0xc000c71ce0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/reflector.go:220 +0x1b5
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x2e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc001232a90, 0xc001258500)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62

goroutine 186 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc000914880, 0x0)
	/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000914870)
	/usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.(*pipe).Read(0xc000914868, 0xc00090ec00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/pipe.go:65 +0x8f
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc000914840, 0xc00090ec00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc000908c60, 0xc000e89ba0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc000908c60, 0x0, 0x0, 0x338fbc0)
	/usr/local/go/src/encoding/json/stream.go:140 +0x1e8
encoding/json.(*Decoder).Decode(0xc000908c60, 0x3427a80, 0xc000e89ba0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc000d62ff0, 0xc00081d000, 0x400, 0x400, 0x0, 0x0, 0x38)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x1a1
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0006aff40, 0x0, 0x4178180, 0xc00090c080, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc000e89b80, 0x0, 0x0, 0x91f166, 0xc000058030, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00090c040)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:71 +0xbe
```

It starts very slowly, and before the errors throw I see the following output (and other endpoints like this as well):

```go
1 request.go:591] Throttling request took 396.994032ms, request: GET:https://10.100.0.1:443/api/v1/replicationcontrollers?limit=500&resourceVersion=0
I0219 03:53:30.941165       1 request.go:591] Throttling request took 396.73066ms, request: GET:https://10.100.0.1:443/api/v1/pods?limit=500&resourceVersion=0

I0219 13:31:36.171821       1 aws_util.go:76] fetching https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.json
W0219 13:32:06.172190       1 aws_util.go:79] Error fetching https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.json skipping...
F0219 13:32:06.172219       1 aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list
```

**Anything else we need to know?**:

This happens every time. None of the errors throw and no throttling of the endpoints occurs when not using auto-discovery.

**Comment by bpineau** [comment]
Hi, it's unfortunate [that error details](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_util.go#L78) aren't included in the log call, but it looks like your autoscaler pod can't reach that public endpoint (`https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.json`) for some reason: it might be possible to verify why by curl'ing  that url from the pod (or an other pod in the same network context)?

Alternatively, you can use the `--aws-use-static-instance-list` flags (the autoscaler will then use a builtin, static instance types list (that might get outdated after a while though) instead of fetching it dynamically).

**Comment by danthegoodman1** [comment]
@bpineau In doing so I found out that endpoint has an enormous response (about 111MB) for the configured 300MB of RAM requested for the pod, so that could contribute. It seems like, with a few adjustments, the pod is running more reliably. At least it restarts and keeps trying until it gets a response.

**Comment by crechandan** [comment]
Hello

Is there any solution for this error. 

Can someone guide me - how to use --aws-use-static-instance-list flag if I am deploying Cluster Autoscaler 1.20 via helm chart https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler/9.9.0 

BR,
Chandan

**Comment by cboyle-vmware** [comment]
Hit this issue and tracked it down to the pod not having enough resources. We had memory request and limit set to 300m, bumped up 500m and the pods were able to process the instance type list.

Adding `--aws-use-static-instance-list` also worked without increasing pod resources.
