### ISSUE TITLE
Errors for install cluster autoscaler on GCE 

### ISSUE THREAD

**Issue by Leisureroad** [kubernetes/autoscaler#4475]
**Which component are you using?**: cluster-autoscaler helm charts

**What version of the component are you using?**:
Helm Chart: apiVersion: v2
appVersion: 1.21.1

Component version: 
Helm: version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
Google Compute Engine + CentOS 7

**What did you expect to happen?**:
Install cluster autoscaler successfully via Helm.

**What happened instead?**:
There is an error in the autoscaler pod,
Failed to get nodes from apiserver: Get "https://172.16.16.1:443/api/v1/nodes": dial tcp 172.16.16.1:443: i/o timeout
goroutine 1 [running]:

But actually my control plane is:
Kubernetes control plane is running at https://10.122.16.2:6443

Is it possible to specify the control plane address via helm command line? I did try to use --kube-apiserver, --kube-context, but all of them don't work.

**How to reproduce it (as minimally and precisely as possible)**:
1. install Kubernetes control plane and work nodes on GCE with CentOS7
2. create instance template for GCE and managed instance group based on instance template
3. install cluster autoscaler with helm
/usr/local/bin/helm install autoscaler autoscaler/cluster-autoscaler --set "autoscalingGroupsnamePrefix[0].name=k8s-autoscaler-ig" --set "autoscalingGroupsnamePrefix[0].maxSize=10" --set "autoscalingGroupsnamePrefix[0].minSize=1" --set autoDiscovery.clusterName=k8s-autoscaler --set cloudProvider=gce

**Anything else we need to know?**:

**Comment by Leisureroad** [comment]
I modified the k8s deployment manually, add one more parameter "--kubernetes=https://10.122.16.2:6443" to specify the kubernetes control plane address, but still timeout error,

F1122 08:49:06.367756       1 main.go:420] Failed to get nodes from apiserver: Get "https://10.122.16.2:6443/api/v1
/nodes": dial tcp 10.122.16.2:6443: i/o timeout
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00012a001, 0xc000718000, 0xa3, 0x1b3)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1021 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x629d5a0, 0xc000000003, 0x0, 0x0, 0xc0002a4070, 0x617f4a9, 0x7, 0x1a4, 0x0)
        /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:970 +0x1a3
k8s.io/klog/v2.(*loggingT).printf(0x629d5a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x3e4d4fa, 0x26, 0xc000349130, 0x1, 
...)
