### ISSUE TITLE
[aws-cluster-autoscaler][9.16.2/9.17.2] Failed to generate AWS EC2 Instance Types: MissingEndpoint: 'Endpoint' configuration is required for this service

### ISSUE THREAD

**Issue by PavelSusloparov** [kubernetes/autoscaler#4780]
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: cluster-autoscaler

Component version: 9.16.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: pod is in a healthy state

**What happened instead?**: pod fails with the error message - "[aws_cloud_provider.go:369] Failed to generate AWS EC2 Instance Types: MissingEndpoint: 'Endpoint' configuration is required for this service"

**How to reproduce it (as minimally and precisely as possible)**: 

```
resource "helm_release" "cluster_autoscaler" {
  count      = var.enable_cluster_autoscaler ? 1 : 0
  name       = "cluster-autoscaler"
  repository = "https://kubernetes.github.io/autoscaler"
  chart      = "cluster-autoscaler"
  version    = "9.16.2"

  namespace = "kube-system"

  set {
    name  = "autoDiscovery.clusterName"
    value = var.cluster_id
  }

  set {
    name  = "awsRegion"
    value = var.region
  }

  values = var.cluster_autoscaler_values
}
```
where var.cluster_id is "test2".
and var.cluster_autoscaler_values is []

managed groups configuration for AWS EKS:
```
eks_managed_node_groups = {
    primary = {
      name = "node_group_main"
      iam_role_additional_policies = [
        "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      ]
      allow_access_ingress_cidr_blocks = [
        module.account_customizations.vpc_cidr_block_us_east_2
      ]
      instance_types   = ["t3.medium"]
      desired_size     = 2
      min_size         = 2
      max_size         = 5
      subnet_ids       = module.account_customizations.private_subnets_us_east_2
      tags = {
        "k8s.io/cluster-autoscaler/enabled" = "true"
        "k8s.io/cluster-autoscaler/test2"   = "owned"
      }
    }
  }
```

**Anything else we need to know?**: Need guidance with what I'm missing in the configuration.

```
W0401 20:14:08.396936       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget                                       │
│ I0401 20:14:08.404065       1 cloud_provider_builder.go:29] Building aws cloud provider.                                                                                                                 │
│ F0401 20:14:08.404683       1 aws_cloud_provider.go:369] Failed to generate AWS EC2 Instance Types: MissingEndpoint: 'Endpoint' configuration is required for this service                               │
│ goroutine 59 [running]:                                                                                                                                                                                  │
│ k8s.io/klog/v2.stacks(0x1)                                                                                                                                                                               │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a                                                                                                            │
│ k8s.io/klog/v2.(*loggingT).output(0x611e4e0, 0x3, 0x0, 0xc00031c620, 0x0, {0x4d2e584, 0x1}, 0xc0009f15f0, 0x0)                                                                                           │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd                                                                                                            │
│ k8s.io/klog/v2.(*loggingT).printf(0x203000, 0x203000, 0x0, {0x0, 0x0}, {0x3cd1b88, 0x2d}, {0xc0009f15f0, 0x1, 0x1})                                                                                      │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:753 +0x1c5                                                                                                            │
│ k8s.io/klog/v2.Fatalf(...)                                                                                                                                                                               │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1532                                                                                                                  │
│ k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.BuildAWS({{0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000}, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, ...}, ...)        │
│     /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:369 +0x3f7
```

**Comment by PavelSusloparov** [comment]
Still have this problem in 9.17.2

**Comment by PavelSusloparov** [comment]
I did a little bit of digging.
The cluster autoscaller endpoint is not ready.


```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-04-20T18:58:04Z"
  creationTimestamp: "2022-04-20T18:45:30Z"
  labels:
    app.kubernetes.io/instance: cluster-autoscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-cluster-autoscaler
    helm.sh/chart: cluster-autoscaler-9.17.2
  name: cluster-autoscaler-aws-cluster-autoscaler
  namespace: kube-system
  resourceVersion: "578662"
  uid: 3fb2d7b3-03a6-4e3e-ad18-b36f0e86b987
subsets:
- notReadyAddresses:
  - ip: 10.11.101.233
    nodeName: ip-10-11-101-218.us-east-2.compute.internal
    targetRef:
      kind: Pod
      name: cluster-autoscaler-aws-cluster-autoscaler-84785b7764-fm6xg
      namespace: kube-system
      resourceVersion: "578660"
      uid: a8965501-f45f-424c-b32a-53477e0d52dd
  ports:
  - name: http
    port: 8085
    protocol: TCP
```

I expect the key to be
```
addresses
```
instead of
```
notReadyAddresses
```

**Comment by PavelSusloparov** [comment]
My suspicion is related to the networking rules restrictions in-between the node group security group and the EKS cluster security group.
