### ISSUE TITLE
cluster-autoscaler pod crashing without clear message after obtaining the lease

### ISSUE THREAD

**Issue by vgauzzi** [kubernetes/autoscaler#5086]
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
1.20.3

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-18ef993", GitCommit:"77b5697130c2dea4087e1009638e21cc93f5c5b6", GitTreeState:"clean", BuildDate:"2022-07-06T18:04:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
Amazon EKS

**What did you expect to happen?**:
The cluster-autoscaler pod should launch and get to a healthy state

**What happened instead?**:
Pod crashes without a clear error message

**How to reproduce it (as minimally and precisely as possible)**:
Start cluster-autoscaler 1.20.3 from the helm chart 9.9.2 on platform version 'eks.8'

**Anything else we need to know?**:

Important to note:  Our CA worked on EKS 1.20 platform version 'eks.7' ... we created however a new cluster - also EKS .120, but the platform version was automatically updated to 'eks.8'.

This are the logs from the crashing Pods:

```
I0812 14:53:51.574190       1 aws_cloud_provider.go:377] Successfully load 591 EC2 Instance Types [m6i r6i.xlarge g4dn.16xlarge r5.24xlarge m5zn r5d.16xlarge r6g.xlarge mac1 r5d.4xlarge r5b.8xlarge c6g.8xlarge c6g.4xlarge c4.large r6a.12xlarge r5.large c6gd.4xlarge u-12tb1.112xlarge t3a.small r5dn.large x2iedn m6i.8xlarge im4gn.large m6gd.16xlarge r5dn r6g.16xlarge m5dn.large d3en.6xlarge m5n r6i.2xlarge c6i.4xlarge r3.2xlarge c5n m3.large m6g.12xlarge i3p.16xlarge t3 t2.micro m5d.2xlarge r5d.metal r5dn.8xlarge c5.9xlarge h1 g4dn.metal r4.16xlarge x2iedn.16xlarge g2.2xlarge mac1.metal c5a.12xlarge m5.16xlarge g4dn.4xlarge g4ad.4xlarge mac2.metal i4i.large g5.12xlarge r6gd.2xlarge i3en c6i.24xlarge c5ad.large m5dn.xlarge m5n.8xlarge c6g.12xlarge m5n.large r6g.metal a1.metal m5zn.12xlarge m5.metal z1d.6xlarge t3.xlarge r5b.metal t3a.2xlarge c5ad.4xlarge g5.xlarge c1.xlarge c5d.12xlarge m6i.metal m5zn.6xlarge g4dn.12xlarge c5ad.2xlarge c1.medium m6a.12xlarge t4g.large m5d.large u-9tb1.112xlarge g5.24xlarge i4i.32xlarge m5n.12xlarge c5n.4xlarge c5d.18xlarge g3.16xlarge inf1 c6gn.xlarge m6g.large p3.16xlarge m3.xlarge m5a.8xlarge i3en.24xlarge c3.large f1.4xlarge u-12tb1 p3dn r5ad.xlarge g4ad.2xlarge c5d c5d.24xlarge r6a.xlarge r6i.large m5d.metal i2.8xlarge r5d.xlarge p3dn.24xlarge r5a.12xlarge i2.xlarge c6a.12xlarge r5 m5a.4xlarge r5ad.large t2.xlarge t4g.micro r6g.medium r5ad.8xlarge c6a r6gd i3.large t3.large g5.8xlarge g5.2xlarge m6a.2xlarge r6a.32xlarge m6a.metal x2iedn.4xlarge r6g.2xlarge r5.xlarge g3 m6g.8xlarge x2gd.16xlarge r5.8xlarge r5n.12xlarge r5dn.2xlarge i2.2xlarge r6gd.12xlarge p4d i2.large im4gn r5a.16xlarge a1.xlarge t2.small c5a.8xlarge c6gn.16xlarge r4 h1.4xlarge d3en.8xlarge x1e.8xlarge d2.xlarge m5ad.large m6i.xlarge m5zn.metal g3.8xlarge c3.xlarge c5d.2xlarge d2.8xlarge i4i.8xlarge c6g.large r6gd.8xlarge x2gd.metal f1 m6a m5.4xlarge r6a.large r6g.large is4gen.large is4gen.2xlarge t3a.nano m4.large m5zn.2xlarge c3.4xlarge m5.large c3.8xlarge x1e.2xlarge g2.8xlarge m4 f1.16xlarge m6gd.4xlarge m5n.metal c6i.2xlarge r6gd.metal g5g.metal m2.xlarge r5dn.xlarge m4.10xlarge g5.16xlarge m6gd.8xlarge m3.2xlarge t3a.micro g4ad.16xlarge c4.xlarge c5n.2xlarge c6i.xlarge m5zn.large is4gen.8xlarge i4i.2xlarge z1d.3xlarge d2.2xlarge m5d.16xlarge m6gd.xlarge p3.8xlarge m1.small x2gd.medium c5.large r5a.24xlarge r6a.2xlarge m6a.16xlarge i2.4xlarge c5a.24xlarge c5d.4xlarge r4.4xlarge t1.micro c6a.48xlarge r5a.4xlarge r6i.4xlarge m5d.xlarge m6a.large m5dn.8xlarge r5n g5g.2xlarge dl1 hs1.8xlarge r6a.16xlarge i4i.xlarge m6gd p3 m5ad.4xlarge x1e.16xlarge c6g.16xlarge r3 r5.4xlarge m5zn.3xlarge i3.16xlarge x2idn t3.small r6gd.16xlarge r5d m5 r5n.16xlarge m5a.12xlarge vt1.24xlarge r5n.2xlarge r6a.4xlarge c6gd.medium c5 im4gn.8xlarge i3.xlarge m5ad.12xlarge t4g.xlarge c5d.9xlarge r5.2xlarge t3.medium x2idn.32xlarge i3 c6gn.metal vt1.6xlarge c6i g5g.8xlarge c5n.metal r5ad.12xlarge r5d.8xlarge u-6tb1.metal c5ad.xlarge m4.xlarge c6gn.12xlarge r6a r6i.8xlarge a1.large c6gn.4xlarge c6i.large g5g u-24tb1 i3.4xlarge i3en.3xlarge m5n.xlarge m5d.24xlarge z1d.metal r5a.large g4dn c5d.metal p2.xlarge m5ad.2xlarge m6g.medium m6a.xlarge r5dn.12xlarge i4i.16xlarge r6g.4xlarge r5a.8xlarge t3.micro m6a.32xlarge c5a.xlarge t4g.2xlarge c5n.large u-3tb1.56xlarge c6gn.medium c5.4xlarge t3.nano t2.large d3.8xlarge inf1.6xlarge p2.8xlarge c6gd.2xlarge h1.2xlarge r6i.24xlarge c6a.metal c5.xlarge z1d.large cr1.8xlarge c6i.32xlarge m6g.xlarge r5b.24xlarge x1e.32xlarge m6i.24xlarge t3a.large m6a.4xlarge g5.48xlarge m2.4xlarge u-18tb1.metal c5.12xlarge t3a.medium z1d d2 m6gd.medium cc2.8xlarge c6a.16xlarge r5.metal r5n.24xlarge r5ad.2xlarge m5dn.12xlarge m6i.2xlarge t4g.medium m2.2xlarge g5g.xlarge d2.4xlarge c5.24xlarge i3en.6xlarge g5.4xlarge c3.2xlarge i3en.metal c6g.2xlarge i4i.4xlarge r3.large c5n.18xlarge g5g.16xlarge z1d.2xlarge r5ad.4xlarge c6a.32xlarge g4dn.xlarge x2gd.12xlarge m5d.8xlarge x1.32xlarge r5b.4xlarge r5ad.24xlarge c6gn.8xlarge c4 x2gd.2xlarge m3 x2gd.8xlarge u-24tb1.metal i3en.12xlarge m5.xlarge m6gd.2xlarge m6g g4dn.2xlarge m5a.24xlarge c5a.16xlarge r6i.12xlarge x2idn.24xlarge x2iedn.2xlarge c6a.xlarge m6g.16xlarge m5a.2xlarge m5a.large r5dn.metal i4i r5n.4xlarge m6a.48xlarge c6a.8xlarge m5ad.24xlarge im4gn.4xlarge c6i.metal c6g.medium u-6tb1.56xlarge is4gen.medium g4ad.8xlarge m1.xlarge r6g.12xlarge h1.8xlarge r5ad.16xlarge m5.12xlarge a1.medium g3.4xlarge c6g d3en.4xlarge vt1 c5n.xlarge r5d.2xlarge r5n.8xlarge r5.16xlarge x1e.xlarge c6a.2xlarge c6gd.8xlarge i3en.2xlarge c5d.large c6gd m5a.16xlarge m5.24xlarge r5d.12xlarge r5dn.4xlarge r5n.metal c6gd.12xlarge r5b.16xlarge g4ad r4.xlarge x2iedn.8xlarge u-9tb1 d3en.2xlarge c5ad.24xlarge m4.16xlarge a1 m5.8xlarge r5d.large t2.nano c6a.large m5d.4xlarge r6gd.4xlarge m5dn.4xlarge u-18tb1 x2iedn.xlarge r5n.large f1.2xlarge u-9tb1.metal m5ad.8xlarge x2gd.large inf1.xlarge m4.4xlarge c4.2xlarge t3.2xlarge r6a.8xlarge r5n.xlarge r5.12xlarge c6gd.16xlarge p2 r5d.24xlarge c5n.9xlarge p2.16xlarge p4d.24xlarge m6i.4xlarge c3 m4.2xlarge m5dn.16xlarge g4ad.xlarge r5b.large m6g.2xlarge r5b m5n.24xlarge a1.4xlarge r4.large c4.8xlarge x2iedn.24xlarge i3en.large c6gn c6a.24xlarge m6gd.large d3.4xlarge m5zn.xlarge i3en.xlarge t2.2xlarge r6i.32xlarge m5dn.2xlarge c5a.4xlarge d3.2xlarge t4g.nano r6gd.xlarge r5dn.16xlarge r5b.xlarge m5d vt1.3xlarge c6g.xlarge c5a.large c6gd.large i4i.metal x2idn.16xlarge c6i.16xlarge c6i.8xlarge m6i.12xlarge m6g.4xlarge t2.medium r6a.24xlarge d3.xlarge im4gn.2xlarge dl1.24xlarge c5ad.16xlarge r6i.metal inf1.24xlarge r5b.2xlarge g3s.xlarge c6gd.xlarge m5.2xlarge m5dn i3.2xlarge m6gd.12xlarge r6gd.medium g5 r6g.8xlarge i3.8xlarge m5ad.xlarge m6i.large x1e.4xlarge x1e m1.large g2 g5g.4xlarge x1.16xlarge c5ad.12xlarge c5ad.8xlarge r6gd.large r5a.2xlarge u-12tb1.metal is4gen.4xlarge im4gn.16xlarge m5dn.24xlarge z1d.xlarge m5d.12xlarge c4.4xlarge i2 z1d.12xlarge im4gn.xlarge m5n.4xlarge m5a.xlarge g4dn.8xlarge m5n.16xlarge x2gd.4xlarge m1.medium h1.16xlarge r4.2xlarge c6i.12xlarge r5a.xlarge mac2 x2iedn.metal r4.8xlarge r6i c5.18xlarge c6g.metal a1.2xlarge inf1.2xlarge is4gen.xlarge c5d.xlarge t3a.xlarge p3.2xlarge x1 c6gd.metal r6a.metal m5ad.16xlarge r3.4xlarge c6gn.2xlarge r6g t4g.small u-6tb1 r6i.16xlarge r6a.48xlarge x2iedn.32xlarge m5n.2xlarge m6a.8xlarge d3en.12xlarge r5b.12xlarge m3.medium c6a.4xlarge r3.8xlarge x2idn.metal m6gd.metal x2gd c6gn.large c5.2xlarge c5a.2xlarge m6g.metal i3.metal u-6tb1.112xlarge c5.metal d3en.xlarge m5dn.metal m6a.24xlarge m6i.32xlarge x2gd.xlarge r5dn.24xlarge r3.xlarge m6i.16xlarge]
I0812 14:53:51.831963       1 leaderelection.go:273] successfully renewed lease kube-addons/cluster-autoscaler
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc004a7e5c0, 0x6d69547461656274, 0x32323032223a2265, 0x923666, 0xc000128008, 0x0, 0x6f697469736e6172)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc004780140)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:71 +0xbe

goroutine 243 [select]:
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache.(*processorListener).pop(0xc00105aa80)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/cache/shared_informer.go:742 +0x15a
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0006d7800, 0xc0009d30b0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62

goroutine 257 [sync.Cond.Wait]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0009cae00, 0x0)
    /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0009cadf0)
    /usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.(*pipe).Read(0xc0009cade8, 0xc000825200, 0x200, 0x200, 0x0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/pipe.go:65 +0x8f
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc0009cadc0, 0xc000825200, 0x200, 0x200, 0x0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc0009cbce0, 0xc000e7d360, 0x3565616561366164)
    /usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc0009cbce0, 0x0, 0x0, 0x33aebc0)
    /usr/local/go/src/encoding/json/stream.go:140 +0x1e8
encoding/json.(*Decoder).Decode(0xc0009cbce0, 0x3446a80, 0xc000e7d360, 0x682d6e6f6974616e, 0x734072656c646e61)
    /usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc000f76870, 0xc00091e400, 0x400, 0x400, 0x2e63696c62757022, 0x77612e726365, 0x38)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x1a1
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc000e3d4f0, 0x0, 0x419ce00, 0xc000f2ae40, 0x657a6973222c5d22, 0x333a227365747942, 0x7d37353235383837, 0x73656d616e227b2c, 0x79617571225b3a22)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc000e7d340, 0x3064656135383961, 0x3938623062366565, 0x3530373465623064, 0x71222c2264633239, 0x702f6f692e796175, 0x75656874656d6f72)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000f2ae00)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:71 +0xbe

goroutine 175 [sync.Cond.Wait]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc005c010c0, 0x0)
    /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc005c010b0)
    /usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.(*pipe).Read(0xc005c010a8, 0xc002628e00, 0x200, 0x200, 0x0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/pipe.go:65 +0x8f
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc005c01080, 0xc002628e00, 0x200, 0x200, 0x0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc005837b80, 0xc005910900, 0x203000)
    /usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc005837b80, 0x0, 0x0, 0x33aebc0)
    /usr/local/go/src/encoding/json/stream.go:140 +0x1e8
encoding/json.(*Decoder).Decode(0xc005837b80, 0x3446a80, 0xc005910900, 0x420ba5, 0xc00592b400)
    /usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc005859380, 0xc001b5d400, 0x400, 0x400, 0x446d6c, 0xc0008fc958, 0x38)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x1a1
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc00584f590, 0x0, 0x419ce00, 0xc00592b400, 0x0, 0xc000296e68, 0xc000d341e0, 0x43780c, 0xc000296e50)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0059108e0, 0xc000296f18, 0xc000296f78, 0x923666, 0xc000128008, 0x0, 0x3)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00592b3c0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:71 +0xbe

goroutine 322 [sync.Cond.Wait]:
runtime.goparkunlock(...)
    /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc006373900, 0x2)
    /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0063738f0)
    /usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.(*pipe).Read(0xc0063738e8, 0xc0036b8001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/pipe.go:65 +0x8f
k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc0063738c0, 0xc0036b8001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/golang.org/x/net/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc006373b80, 0xc005b6400a, 0x9)
    /usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc006373b80, 0x0, 0x0, 0x33aebc0)
    /usr/local/go/src/encoding/json/stream.go:140 +0x1e8
encoding/json.(*Decoder).Decode(0xc006373b80, 0x3446a80, 0xc005b64080, 0x0, 0x0)
    /usr/local/go/src/encoding/json/stream.go:63 +0x79
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc0063ae060, 0xc0036be000, 0x2000, 0x2600, 0x419a980, 0xc0063d1d98, 0x38)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:152 +0x1a1
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0061cbef0, 0x0, 0x419ce00, 0xc005d39940, 0x0, 0xc003883eb8, 0x461ac0, 0xc003883e60, 0xc0063d1e80)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc00638f8e0, 0xc0063d1f18, 0x8, 0x419a980, 0xc005c9c000, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x6e
k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc006211300)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:71 +0xbe
```

**Comment by buettner123** [comment]
Just saw that this looks similar to my issue. Maybe it has the same cause, see https://github.com/kubernetes/autoscaler/issues/5094#issuecomment-1217706040
