### ISSUE TITLE
Flake in AWS cloud provider tests

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/autoscaler#516]
```
--- FAIL: TestFetchAutoAsgs (0.00s)
panic: 
mock: Unexpected Method Call
-----------------------------
DescribeAutoScalingGroupsPages(*autoscaling.DescribeAutoScalingGroupsInput,func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool)
		0: {
  AutoScalingGroupNames: ["coolasg"],
  MaxRecords: 100
}
		1: (func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool)(0x12e7290)
The closest call I have is: 
DescribeAutoScalingGroupsPages(*autoscaling.DescribeAutoScalingGroupsInput,mock.AnythingOfTypeArgument)
		0: {
  AutoScalingGroupNames: ["coolasg"],
  MaxRecords: 100
}
		1: "func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool"
 [recovered]
	panic: 
mock: Unexpected Method Call
-----------------------------
DescribeAutoScalingGroupsPages(*autoscaling.DescribeAutoScalingGroupsInput,func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool)
		0: {
  AutoScalingGroupNames: ["coolasg"],
  MaxRecords: 100
}
		1: (func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool)(0x12e7290)
The closest call I have is: 
DescribeAutoScalingGroupsPages(*autoscaling.DescribeAutoScalingGroupsInput,mock.AnythingOfTypeArgument)
		0: {
  AutoScalingGroupNames: ["coolasg"],
  MaxRecords: 100
}
		1: "func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool"
goroutine 46 [running]:
testing.tRunner.func1(0xc4201d3110)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/testing/testing.go:622 +0x29d
panic(0x14058e0, 0xc42034ba90)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489 +0x2cf
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc4202b1680, 0x21ad60a, 0x1e, 0xc420302420, 0x2, 0x2, 0x4, 0x10, 0xc4204c56d8)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/stretchr/testify/mock/mock.go:311 +0x654
k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/stretchr/testify/mock.(*Mock).Called(0xc4202b1680, 0xc420302420, 0x2, 0x2, 0x10, 0x153cb40, 0x1)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/github.com/stretchr/testify/mock/mock.go:288 +0x14c
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AutoScalingMock).DescribeAutoScalingGroupsPages(0xc4202b1680, 0xc420344300, 0xc42034ae80, 0x227c6b8, 0x0)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:40 +0xa9
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*autoScalingWrapper).getAutoscalingGroupsByNames(0xc4201afa20, 0xc42034ad40, 0x1, 0x1, 0x1, 0x1, 0x30, 0x7fc0a2bbd000, 0x0)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/auto_scaling.go:89 +0x1c2
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*asgCache).regenerate(0xc4201af9f0, 0x1764fc0, 0xc4201afa18)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:154 +0x33a
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).regenerateCache(0xc4201afa40, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:266 +0x8d
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).fetchAutoAsgs(0xc4201afa40, 0x0, 0x22600e0)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:198 +0x685
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).forceRefresh(0xc4201afa40, 0x0, 0x0)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:235 +0x40
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.createAWSManagerInternal(0x0, 0x0, 0x0, 0x0, 0x0, 0xc420045ef0, 0x1, 0x1, 0xc420045ee0, 0x0, ...)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:111 +0x21f
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.TestFetchAutoAsgs(0xc4201d3110)
	/home/travis/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager_test.go:221 +0xab7
testing.tRunner(0xc4201d3110, 0x1762518)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/testing/testing.go:697 +0x2ca
FAIL	k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws	0.149s
```

**Comment by mwielgus** [comment]
cc: @negz
