### ISSUE TITLE
Error from cluster autoscaler v1.22.3 on AWS EKS 1.22 - Couldn't open cloud provider configuration /etc/gce.conf:

### ISSUE THREAD

**Issue by vaibhav-ak** [kubernetes/autoscaler#5243]
Any help on this one. `Cluster autoscaler version is 1.22.3`. We are passing aws region and most other variables. Can't understand why it's trying to look for `/etc/gce.conf`

```
            autoDiscovery:
              clusterName:  # cluster.local
              tags:
                - k8s.io/cluster-autoscaler/enabled
                - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}
              roles:
                - worker
            **cloudProvider: aws**
```

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L370

```


I1010 11:12:38.839447       1 flags.go:52] FLAG: --vmodule=""
I1010 11:12:38.839451       1 flags.go:52] FLAG: --write-status-configmap="true"
I1010 11:12:38.839457       1 main.go:400] Cluster Autoscaler 1.22.3
I1010 11:12:38.928353       1 leaderelection.go:248] attempting to acquire leader lease kube-system/cluster-autoscaler...
I1010 11:12:38.943610       1 leaderelection.go:258] successfully acquired lease kube-system/cluster-autoscaler
I1010 11:12:38.943752       1 event_sink_logging_wrapper.go:48] Event(v1.ObjectReference{Kind:"Lease", Namespace:"kube-system", Name:"cluster-autoscaler", UID:"6465999c-df58-42be-8e30-1a5a68a63238", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"6291490", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' cluster-autoscaler-5b695cf974-247ql became leader
I1010 11:12:38.945047       1 reflector.go:219] Starting reflector *v1.ReplicationController (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:329
I1010 11:12:38.945141       1 reflector.go:255] Listing and watching *v1.ReplicationController from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:329
I1010 11:12:38.945061       1 reflector.go:219] Starting reflector *v1beta1.PodDisruptionBudget (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309
I1010 11:12:38.945180       1 reflector.go:255] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309
I1010 11:12:38.945080       1 reflector.go:219] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:188
I1010 11:12:38.945223       1 reflector.go:255] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:188
I1010 11:12:38.945056       1 reflector.go:219] Starting reflector *v1.Job (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:338
I1010 11:12:38.945295       1 reflector.go:255] Listing and watching *v1.Job from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:338
I1010 11:12:38.945091       1 reflector.go:219] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
I1010 11:12:38.945323       1 reflector.go:255] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
I1010 11:12:38.945095       1 reflector.go:219] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I1010 11:12:38.945400       1 reflector.go:255] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I1010 11:12:38.945098       1 reflector.go:219] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I1010 11:12:38.945423       1 reflector.go:255] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I1010 11:12:38.945105       1 reflector.go:219] Starting reflector *v1.ReplicaSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:347
I1010 11:12:38.945449       1 reflector.go:255] Listing and watching *v1.ReplicaSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:347
I1010 11:12:38.945113       1 reflector.go:219] Starting reflector *v1.DaemonSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:320
I1010 11:12:38.945479       1 reflector.go:255] Listing and watching *v1.DaemonSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:320
I1010 11:12:38.945122       1 reflector.go:219] Starting reflector *v1.StatefulSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:356
I1010 11:12:38.945495       1 reflector.go:255] Listing and watching *v1.StatefulSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:356
W1010 11:12:39.026668       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
I1010 11:12:39.226789       1 cloud_provider_builder.go:29] Building aws cloud provider.
`F1010 11:12:39.226854       1 aws_cloud_provider.go:348] Couldn't open cloud provider configuration /etc/gce.conf: &fs.PathError{Op:"open", Path:"/etc/gce.conf", Err:0x2}`
goroutine 75 [running]:
k8s.io/klog/v2.stacks(0xc0001aa001, 0xc00038ef00, 0xab, 0xf5)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x613f220, 0xc000000003, 0x0, 0x0, 0xc000556d20, 0x0, 0x50bbe64, 0x15, 0x15c, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printf(0x613f220, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x41731b4, 0x32, 0xc000420f80, 0x2, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
k8s.io/klog/v2.Fatalf(...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/klog/v2/klog.go:1514
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.BuildAWS(0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:348 +0xdd2
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder.buildCloudProvider(0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder/builder_all.go:73 +0x1b8
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder.NewCloudProvider(0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/builder/cloud_provider_builder.go:45 +0x230
k8s.io/autoscaler/cluster-autoscaler/core.initializeDefaultOptions(0xc0006b76e8, 0xc0006b74a0, 0x451065)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:101 +0x318
k8s.io/autoscaler/cluster-autoscaler/core.NewAutoscaler(0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:65 +0x45
```

**Comment by vaibhav-ak** [comment]
Using latest chart works - https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler/9.21.0

**Comment by rudimk** [comment]
Think this should be reopened - we're seeing this on EKS 1.24 with the chart version pegged at `9.28.0`.
