### ISSUE TITLE
Empty `cluster-autoscaler-status` configmap results in panic

### ISSUE THREAD

**Issue by james-callahan** [kubernetes/autoscaler#5704]
**Which component are you using?**:

**What version of the component are you using?**:

Component version:
v1.26.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

TalosOS 1.3.7

**What did you expect to happen?**:

working/running daemon

**What happened instead?**:

panic

**How to reproduce it (as minimally and precisely as possible)**:

1. Clear out the `cluster-autoscaler-status` configmap
2. restart the cluster-autoscaler

**Anything else we need to know?**:

```
panic: assignment to entry in nil map

goroutine 72 [running]:
k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils.WriteStatusConfigMap({0x5a5ced8, 0xc000461860}, {0x7ffdc3be3c15, 0x12}, {0xc001bc8d80, 0xd39}, 0xc001ab5920, {0x51162d1, 0x19})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils/status.go:94 +0x42f
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce.func1()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:364 +0x17e
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc00138b9a0, {0x4?, 0xc000077710?, 0x87e5e60?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:657 +0x2f0b
main.run(0xc0004b7900?, {0x5a2aa38, 0xc000aefa10})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:449 +0x2cd
main.main.func2({0x5a20c98?, 0xc000684180?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:536 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
```

**Comment by james-callahan** [comment]
I've updated to `registry.k8s.io/autoscaling/cluster-autoscaler:v1.27.3` and this is still a problem:

```
panic: assignment to entry in nil map
goroutine 75 [running]:
k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils.WriteStatusConfigMap({0x65ad678, 0xc000b324e0}, {0x7ffddc037c0c, 0x12}, {0x5b4b3cb, 0xc}, 0x0, {0x5b827c8, 0x19})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils/status.go:94 +0x42f
k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils.NewStatusMapRecorder({0x65ad678?, 0xc000b324e0?}, {0x7ffddc037c0c?, 0xc000d90058?}, {0x655b840?, 0xc000954280}, 0x1, {0x5b827c8?, 0x65a5f10?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils/status.go:70 +0x6f
k8s.io/autoscaler/cluster-autoscaler/context.NewAutoscalingKubeClients({{0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0xd18c2e2800}, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, ...}, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/context/autoscaling_context.go:128 +0xd7
k8s.io/autoscaler/cluster-autoscaler/core.initializeDefaultOptions(0xc000bbef28)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:97 +0xfe
k8s.io/autoscaler/cluster-autoscaler/core.NewAutoscaler({{{0x3fe0000000000000, 0x3fe0000000000000, 0x8bb2c97000, 0x1176592e000, 0xd18c2e2800}, 0xa, 0x0, 0x4e200, 0x0, 0x186a0000000000, ...}, ...})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/autoscaler.go:72 +0x36
main.buildAutoscaler({0x656ecb0, 0xc000a9af90})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:478 +0xd25
main.run(0x0?, {0x656ecb0, 0xc000a9af90})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:484 +0x65
main.main.func2({0x0?, 0x0?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:596 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:208 +0x105
```
