### ISSUE TITLE
cluster-autoscaler has nil pointer dereference in deleteCreatedNodesWithErrors

### ISSUE THREAD

**Issue by zchenyu** [kubernetes/autoscaler#5884]
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.24.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.13-eks-0a21954", GitCommit:"6305d65c340554ad8b4d7a5f21391c9fa34932cb", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:45Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS EKS with managed node groups

**What did you expect to happen?**:

No segfault

**What happened instead?**:

```
W0623 03:08:49.398829       1 clusterstate.go:594] Nodegroup is nil for aws:///us-west-2a/i-placeholder-eks-m6i-xlarge-a-32c408b0-ad2a-1236-8011-502baf4086b1-25
W0623 03:08:49.398849       1 clusterstate.go:594] Nodegroup is nil for aws:///us-west-2a/i-placeholder-eks-m6i-xlarge-a-32c408b0-ad2a-1236-8011-502baf4086b1-143
I0623 03:08:49.399055       1 clusterstate.go:1008] Found 189 instances with errorCode OutOfResource.placeholder-cannot-be-fulfilled in nodeGroup eks-m6i-xlarge-a-32c408b0-ad2a-1236-8011-502baf4086b1
I0623 03:08:49.399086       1 clusterstate.go:1026] Failed adding 189 nodes (0 unseen previously) to group eks-m6i-xlarge-a-32c408b0-ad2a-1236-8011-502baf4086b1 due to OutOfResource.placeholder-cannot-be-fulfilled; errorMessages=[]string{"AWS cannot provision any more instances for this node group"}
I0623 03:08:49.399161       1 clusterstate.go:1008] Found 27 instances with errorCode OutOfResource.placeholder-cannot-be-fulfilled in nodeGroup eks-r6in-2xlarge-a-b6c408b5-4ce0-7469-da26-3a8780201103
I0623 03:08:49.399176       1 clusterstate.go:1026] Failed adding 27 nodes (0 unseen previously) to group eks-r6in-2xlarge-a-b6c408b5-4ce0-7469-da26-3a8780201103 due to OutOfResource.placeholder-cannot-be-fulfilled; errorMessages=[]string{"AWS cannot provision any more instances for this node group"}
I0623 03:08:49.399261       1 static_autoscaler.go:341] 216 unregistered nodes present
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x3b9cb9a]

goroutine 56 [running]:
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).deleteCreatedNodesWithErrors(0xc00f8fe080)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:677 +0x27a
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc00f8fe080, {0x4?, 0xc000c5e1b8?, 0x8235ca0?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:360 +0x141a
main.run(0x0?, {0x5628fc0, 0xc000b41a70})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:393 +0x2cd
main.main.func2({0x0?, 0x0?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:480 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by qianlei90** [comment]
https://github.com/kubernetes/autoscaler/pull/5804 is not in v1.24.2, but it is in branch `cluster-autoscaler-release-1.24`. Before v1.24.3 released, you can build your own image.

**Comment by Shubham82** [comment]
#5804 is in CA v1.24.3, Here is the release note: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.24.3

**Comment by Shubham82** [comment]
This issue is resolved, so I am closing this issue.
Please reopen it if there is any concern.
