### ISSUE TITLE
helm chart install panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by innovia** [kubernetes/autoscaler#821]
**kubernetes ver:** 1.8.7
**ca version:** 1.0.5

**values.yaml:**

```yaml
autoDiscovery: {}
# Only cloudProvider `aws` and `gce` are supported by auto-discovery at this time
# AWS: Set tags as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
#   clusterName:  # cluster.local

autoscalingGroups:
- name: on-demand-nodes.k8.domain.com
  maxSize: 20
  minSize: 3
- name: spot-nodes.k8.domain.com
  maxSize: 20
  minSize: 0

autoscalingGroupsnamePrefix:
- name: on-demand-nodes
  maxSize: 20
  minSize: 3
- name: spot-nodes
  maxSize: 10
  minSize: 0

# Required if cloudProvider=aws
awsRegion: us-west-2

# Currently only `gce`, `aws` & `spotinst` are supported
cloudProvider: aws

image:
  repository: k8s.gcr.io/cluster-autoscaler
  tag: v1.0.5
  pullPolicy: IfNotPresent

tolerations: []

extraArgs:
  v: 5
  stderrthreshold: info
  logtostderr: true
  # write-status-configmap: true
  leader-elect: true
  expander: least-waste
  scale-down-enabled: true
  balance-similar-node-groups: true
  min-replica-count: 2
  scale-down-utilization-threshold: 0.5
  scale-down-non-empty-candidates-count: 5
  max-node-provision-time: 15m0s
  scan-interval: 10s
  scale-down-unneeded-time: 5m
  skip-nodes-with-local-storage: false
  skip-nodes-with-system-pods: true


## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## affinity: {}

podDisruptionBudget: |
  maxUnavailable: 1
  # minAvailable: 2

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

podAnnotations: {}
podLabels: {}
replicaCount: 1

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true
  ## If true, create & use Pod Security Policy resources
  ## https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  pspEnabled: true
  ## Ignored if rbac.create is true
  ##
  serviceAccountName: default

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 300Mi

service:
  annotations: {}
  clusterIP: ""

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 8085
  portName: http
  type: ClusterIP

spotinst:
  account: ""
  token: ""
  image:
    repository: spotinst/kubernetes-cluster-autoscaler
    tag: 0.6.0
    pullPolicy: IfNotPresent

```

**Rendered Yaml deployment:**
```yaml
# Source: cluster-autoscaler/templates/deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: aws-cluster-autoscaler
    chart: cluster-autoscaler-0.6.1
    heritage: Tiller
    release: autoscale
  name: autoscale-aws-cluster-autoscaler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-cluster-autoscaler
        release: autoscale
    spec:
      containers:
        - name: aws-cluster-autoscaler
          image: "k8s.gcr.io/cluster-autoscaler:v1.0.5"
          imagePullPolicy: "IfNotPresent"
          command:
            - ./cluster-autoscaler
            - --cloud-provider=aws
            - --namespace=default
            - --nodes=3:20:on-demand-nodes.k8.domain.com
            - --nodes=0:20:spot-nodes.k8.domain.com
            - --balance-similar-node-groups=true
            - --expander=least-waste
            - --leader-elect=true
            - --logtostderr=true
            - --max-node-provision-time=15m0s
            - --min-replica-count=2
            - --scale-down-enabled=true
            - --scale-down-non-empty-candidates-count=5
            - --scale-down-unneeded-time=5m
            - --scale-down-utilization-threshold=0.5
            - --scan-interval=10s
            - --skip-nodes-with-local-storage
            - --skip-nodes-with-system-pods=true
            - --stderrthreshold=info
            - --v=4

          env:
            - name: AWS_REGION
              value: "us-west-2"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
          ports:
            - containerPort: 8085
          resources:
            {}

          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
      serviceAccountName: autoscale-aws-cluster-autoscaler
      tolerations:
        []

      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
```
**ca logs**
```
I0430 20:52:11.790915       1 flags.go:52] FLAG: --address=":8085"
I0430 20:52:11.791060       1 flags.go:52] FLAG: --alsologtostderr="false"
I0430 20:52:11.791089       1 flags.go:52] FLAG: --application-metrics-count-limit="100"
I0430 20:52:11.791113       1 flags.go:52] FLAG: --azure-container-registry-config=""
I0430 20:52:11.791139       1 flags.go:52] FLAG: --balance-similar-node-groups="true"
I0430 20:52:11.791159       1 flags.go:52] FLAG: --boot-id-file="/proc/sys/kernel/random/boot_id"
I0430 20:52:11.791194       1 flags.go:52] FLAG: --cloud-config=""
I0430 20:52:11.791219       1 flags.go:52] FLAG: --cloud-provider="aws"
I0430 20:52:11.791240       1 flags.go:52] FLAG: --cloud-provider-gce-lb-src-cidrs="35.191.0.0/16,209.85.152.0/22,209.85.204.0/22,130.211.0.0/22"
I0430 20:52:11.791268       1 flags.go:52] FLAG: --cluster-name=""
I0430 20:52:11.791288       1 flags.go:52] FLAG: --configmap=""
I0430 20:52:11.791307       1 flags.go:52] FLAG: --container-hints="/etc/cadvisor/container_hints.json"
I0430 20:52:11.791337       1 flags.go:52] FLAG: --cores-total="0:320000"
I0430 20:52:11.791359       1 flags.go:52] FLAG: --docker="unix:///var/run/docker.sock"
I0430 20:52:11.791383       1 flags.go:52] FLAG: --docker-env-metadata-whitelist=""
I0430 20:52:11.791405       1 flags.go:52] FLAG: --docker-only="false"
I0430 20:52:11.791428       1 flags.go:52] FLAG: --docker-root="/var/lib/docker"
I0430 20:52:11.791450       1 flags.go:52] FLAG: --docker-tls="false"
I0430 20:52:11.791472       1 flags.go:52] FLAG: --docker-tls-ca="ca.pem"
I0430 20:52:11.791496       1 flags.go:52] FLAG: --docker-tls-cert="cert.pem"
I0430 20:52:11.791529       1 flags.go:52] FLAG: --docker-tls-key="key.pem"
I0430 20:52:11.791552       1 flags.go:52] FLAG: --enable-load-reader="false"
I0430 20:52:11.791575       1 flags.go:52] FLAG: --estimator="binpacking"
I0430 20:52:11.791596       1 flags.go:52] FLAG: --event-storage-age-limit="default=0"
I0430 20:52:11.791616       1 flags.go:52] FLAG: --event-storage-event-limit="default=0"
I0430 20:52:11.791638       1 flags.go:52] FLAG: --expander="least-waste"
I0430 20:52:11.791659       1 flags.go:52] FLAG: --gke-api-endpoint=""
I0430 20:52:11.791678       1 flags.go:52] FLAG: --global-housekeeping-interval="1m0s"
I0430 20:52:11.791704       1 flags.go:52] FLAG: --google-json-key=""
I0430 20:52:11.791727       1 flags.go:52] FLAG: --housekeeping-interval="10s"
I0430 20:52:11.791751       1 flags.go:52] FLAG: --httptest.serve=""
I0430 20:52:11.791783       1 flags.go:52] FLAG: --kubeconfig=""
I0430 20:52:11.791806       1 flags.go:52] FLAG: --kubernetes=""
I0430 20:52:11.791828       1 flags.go:52] FLAG: --leader-elect="true"
I0430 20:52:11.791853       1 flags.go:52] FLAG: --leader-elect-lease-duration="15s"
I0430 20:52:11.791878       1 flags.go:52] FLAG: --leader-elect-renew-deadline="10s"
I0430 20:52:11.791899       1 flags.go:52] FLAG: --leader-elect-resource-lock="endpoints"
I0430 20:52:11.791921       1 flags.go:52] FLAG: --leader-elect-retry-period="2s"
I0430 20:52:11.791943       1 flags.go:52] FLAG: --log-backtrace-at=":0"
I0430 20:52:11.791974       1 flags.go:52] FLAG: --log-cadvisor-usage="false"
I0430 20:52:11.791997       1 flags.go:52] FLAG: --log-dir=""
I0430 20:52:11.792024       1 flags.go:52] FLAG: --logtostderr="true"
I0430 20:52:11.792049       1 flags.go:52] FLAG: --machine-id-file="/etc/machine-id,/var/lib/dbus/machine-id"
I0430 20:52:11.792073       1 flags.go:52] FLAG: --max-autoprovisioned-node-group-count="15"
I0430 20:52:11.792094       1 flags.go:52] FLAG: --max-empty-bulk-delete="10"
I0430 20:52:11.792114       1 flags.go:52] FLAG: --max-failing-time="15m0s"
I0430 20:52:11.792135       1 flags.go:52] FLAG: --max-graceful-termination-sec="600"
I0430 20:52:11.792155       1 flags.go:52] FLAG: --max-inactivity="10m0s"
I0430 20:52:11.792176       1 flags.go:52] FLAG: --max-node-provision-time="15m0s"
I0430 20:52:11.792200       1 flags.go:52] FLAG: --max-nodes-total="0"
I0430 20:52:11.792223       1 flags.go:52] FLAG: --max-total-unready-percentage="33"
I0430 20:52:11.792248       1 flags.go:52] FLAG: --memory-total="0:6400000"
I0430 20:52:11.792282       1 flags.go:52] FLAG: --min-replica-count="2"
I0430 20:52:11.792305       1 flags.go:52] FLAG: --namespace="default"
I0430 20:52:11.792327       1 flags.go:52] FLAG: --node-autoprovisioning-enabled="false"
I0430 20:52:11.792348       1 flags.go:52] FLAG: --node-group-auto-discovery=""
I0430 20:52:11.792367       1 flags.go:52] FLAG: --nodes="[3:20:on-demand-nodes.k8.domain.com 0:20:spot-nodes.k8.domain.com]"
I0430 20:52:11.792392       1 flags.go:52] FLAG: --ok-total-unready-count="3"
I0430 20:52:11.792413       1 flags.go:52] FLAG: --scale-down-candidates-pool-min-count="50"
I0430 20:52:11.792438       1 flags.go:52] FLAG: --scale-down-candidates-pool-ratio="0.1"
I0430 20:52:11.792463       1 flags.go:52] FLAG: --scale-down-delay-after-add="10m0s"
I0430 20:52:11.792487       1 flags.go:52] FLAG: --scale-down-delay-after-delete="10s"
I0430 20:52:11.792509       1 flags.go:52] FLAG: --scale-down-delay-after-failure="3m0s"
I0430 20:52:11.792570       1 flags.go:52] FLAG: --scale-down-enabled="true"
I0430 20:52:11.792595       1 flags.go:52] FLAG: --scale-down-non-empty-candidates-count="5"
I0430 20:52:11.792619       1 flags.go:52] FLAG: --scale-down-unneeded-time="5m0s"
I0430 20:52:11.792640       1 flags.go:52] FLAG: --scale-down-unready-time="20m0s"
I0430 20:52:11.792662       1 flags.go:52] FLAG: --scale-down-utilization-threshold="0.5"
I0430 20:52:11.792685       1 flags.go:52] FLAG: --scan-interval="10s"
I0430 20:52:11.792707       1 flags.go:52] FLAG: --skip-nodes-with-local-storage="true"
I0430 20:52:11.792727       1 flags.go:52] FLAG: --skip-nodes-with-system-pods="true"
I0430 20:52:11.792748       1 flags.go:52] FLAG: --stderrthreshold="0"
I0430 20:52:11.792774       1 flags.go:52] FLAG: --storage-driver-buffer-duration="1m0s"
I0430 20:52:11.792796       1 flags.go:52] FLAG: --storage-driver-db="cadvisor"
I0430 20:52:11.792828       1 flags.go:52] FLAG: --storage-driver-host="localhost:8086"
I0430 20:52:11.792852       1 flags.go:52] FLAG: --storage-driver-password="root"
I0430 20:52:11.792874       1 flags.go:52] FLAG: --storage-driver-secure="false"
I0430 20:52:11.792895       1 flags.go:52] FLAG: --storage-driver-table="stats"
I0430 20:52:11.792914       1 flags.go:52] FLAG: --storage-driver-user="root"
I0430 20:52:11.792935       1 flags.go:52] FLAG: --unregistered-node-removal-time="15m0s"
I0430 20:52:11.792956       1 flags.go:52] FLAG: --v="5"
I0430 20:52:11.792976       1 flags.go:52] FLAG: --version="false"
I0430 20:52:11.793007       1 flags.go:52] FLAG: --vmodule=""
I0430 20:52:11.793033       1 flags.go:52] FLAG: --write-status-configmap="true"
I0430 20:52:11.793063       1 main.go:287] Cluster Autoscaler 1.0.5
I0430 20:52:11.837697       1 leaderelection.go:174] attempting to acquire leader lease...
I0430 20:52:11.878225       1 leaderelection.go:184] successfully acquired lease default/cluster-autoscaler
I0430 20:52:11.878761       1 factory.go:33] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"cluster-autoscaler", UID:"d650f8f5-ceb7-11e7-bf8c-06b53f858278", APIVersion:"v1", ResourceVersion:"50510892", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' autoscale-aws-cluster-autoscaler-6b7b69d5f7-hpnpg became leader
I0430 20:52:11.879699       1 predicates.go:123] Using predicate PodFitsResources
I0430 20:52:11.879750       1 predicates.go:123] Using predicate GeneralPredicates
I0430 20:52:11.879772       1 predicates.go:123] Using predicate PodToleratesNodeTaints
I0430 20:52:11.879797       1 predicates.go:123] Using predicate NoVolumeZoneConflict
I0430 20:52:11.879819       1 predicates.go:123] Using predicate CheckNodeDiskPressure
I0430 20:52:11.879835       1 predicates.go:123] Using predicate MatchInterPodAffinity
I0430 20:52:11.879852       1 predicates.go:123] Using predicate MaxAzureDiskVolumeCount
I0430 20:52:11.879868       1 predicates.go:123] Using predicate NoDiskConflict
I0430 20:52:11.879954       1 predicates.go:123] Using predicate NoVolumeNodeConflict
I0430 20:52:11.879994       1 predicates.go:123] Using predicate CheckNodeCondition
I0430 20:52:11.880015       1 predicates.go:123] Using predicate MaxEBSVolumeCount
I0430 20:52:11.880010       1 reflector.go:202] Starting reflector *v1.Node (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.880048       1 reflector.go:240] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.880035       1 predicates.go:123] Using predicate CheckNodeMemoryPressure
I0430 20:52:11.880279       1 predicates.go:123] Using predicate MaxGCEPDVolumeCount
I0430 20:52:11.880288       1 predicates.go:123] Using predicate ready
I0430 20:52:11.880439       1 reflector.go:202] Starting reflector *v1beta1.ReplicaSet (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.880534       1 reflector.go:240] Listing and watching *v1beta1.ReplicaSet from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.880626       1 reflector.go:202] Starting reflector *v1beta1.DaemonSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:293
I0430 20:52:11.880639       1 reflector.go:240] Listing and watching *v1beta1.DaemonSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:293
I0430 20:52:11.881070       1 reflector.go:202] Starting reflector *v1.PersistentVolume (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881118       1 reflector.go:240] Listing and watching *v1.PersistentVolume from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881356       1 reflector.go:202] Starting reflector *v1beta1.StatefulSet (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881374       1 reflector.go:240] Listing and watching *v1beta1.StatefulSet from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881682       1 reflector.go:202] Starting reflector *v1.PersistentVolumeClaim (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881728       1 reflector.go:240] Listing and watching *v1.PersistentVolumeClaim from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881912       1 reflector.go:202] Starting reflector *v1.Pod (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.881969       1 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.882186       1 reflector.go:202] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:149
I0430 20:52:11.882205       1 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:149
I0430 20:52:11.882326       1 reflector.go:202] Starting reflector *v1.Service (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.882354       1 reflector.go:240] Listing and watching *v1.Service from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.882414       1 reflector.go:202] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174
I0430 20:52:11.882426       1 reflector.go:240] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:174
I0430 20:52:11.882717       1 reflector.go:202] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
I0430 20:52:11.882736       1 reflector.go:240] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
I0430 20:52:11.882942       1 reflector.go:202] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:239
I0430 20:52:11.882955       1 reflector.go:240] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:239
I0430 20:52:11.883049       1 reflector.go:202] Starting reflector *v1.ReplicationController (0s) from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.883079       1 reflector.go:240] Listing and watching *v1.ReplicationController from k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/informers/factory.go:73
I0430 20:52:11.883216       1 reflector.go:202] Starting reflector *v1beta1.PodDisruptionBudget (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:266
I0430 20:52:11.883233       1 reflector.go:240] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:266
I0430 20:52:12.079362       1 request.go:462] Throttling request took 196.135393ms, request: GET:https://100.64.0.1:443/api/v1/replicationcontrollers?resourceVersion=0
I0430 20:52:12.279367       1 request.go:462] Throttling request took 313.490271ms, request: PUT:https://100.64.0.1:443/api/v1/namespaces/default/configmaps/cluster-autoscaler-status
I0430 20:52:12.284473       1 main.go:222] Registered cleanup signal handler
I0430 20:52:12.284524       1 auto_scaling_groups.go:83] Regenerating ASG information for on-demand-nodes.k8.domain.com
I0430 20:52:12.373991       1 auto_scaling_groups.go:83] Regenerating ASG information for spot-nodes.k8.domain.com
I0430 20:52:13.885820       1 leaderelection.go:199] successfully renewed lease default/cluster-autoscaler
I0430 20:52:15.893793       1 leaderelection.go:199] successfully renewed lease default/cluster-autoscaler
I0430 20:52:17.901802       1 leaderelection.go:199] successfully renewed lease default/cluster-autoscaler
I0430 20:52:19.910163       1 leaderelection.go:199] successfully renewed lease default/cluster-autoscaler
I0430 20:52:21.918931       1 leaderelection.go:199] successfully renewed lease default/cluster-autoscaler
I0430 20:52:22.284700       1 static_autoscaler.go:97] Starting main loop
I0430 20:52:22.423825       1 auto_scaling_groups.go:83] Regenerating ASG information for on-demand-nodes.k8.domain.com
I0430 20:52:22.445508       1 auto_scaling_groups.go:83] Regenerating ASG information for spot-nodes.k8.domain.com
I0430 20:52:22.470275       1 static_autoscaler.go:225] Filtering out schedulables
I0430 20:52:22.470729       1 static_autoscaler.go:235] No schedulable pods
I0430 20:52:22.470782       1 scale_up.go:54] Pod redash/redash-server-gunicorn-5597786cc5-cmwtn is unschedulable
I0430 20:52:22.470793       1 scale_up.go:54] Pod redash/redash-server-gunicorn-5597786cc5-bttf2 is unschedulable
I0430 20:52:22.470797       1 scale_up.go:54] Pod redash/redash-server-gunicorn-5597786cc5-cqlnx is unschedulable
W0430 20:52:22.555857       1 aws_manager.go:225] Found multiple availability zones, using us-west-2a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1451b0d]

goroutine 46 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).buildNodeFromTemplate(0xc420c37aa0, 0xc420f5e330, 0xc42130a780, 0xc42130a780, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:252 +0x48d
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*Asg).TemplateNodeInfo(0xc420f5e330, 0xc4208eec30, 0x7fff30213764, 0x21)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:355 +0x78
k8s.io/autoscaler/cluster-autoscaler/core.GetNodeInfosForGroups(0xc420edf040, 0x4, 0x4, 0x50bd320, 0xc420f5e210, 0x50c76e0, 0xc420905e10, 0xc420d2f120, 0x4, 0x4, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/utils.go:211 +0x65a
k8s.io/autoscaler/cluster-autoscaler/core.ScaleUp(0xc420c8b860, 0xc420d2f0a0, 0x3, 0x4, 0xc420edf040, 0x4, 0x4, 0xc420d2f120, 0x4, 0x4, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:57 +0x28e
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc420f7c070, 0xed2797906, 0xe10f7a4a1, 0x51902a0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:252 +0x13ea
main.run(0xc420a53ae0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:263 +0x474
main.main.func2(0xc420265860)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:345 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:145 +0x97
```

**Comment by innovia** [comment]
ok this seems like 1.0.x is not able to scale c5 instances

still think that there should be an error message and not a sigsev panic

**Comment by aleksandra-malinowska** [comment]
> still think that there should be an error message and not a sigsev panic

Completely agree. Would you be interested in contributing to this?
