### ISSUE TITLE
Azure AKS Kubernetes error "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by dhirenrouterabbit** [kubernetes/autoscaler#863]
Kuberentes version: 1.8.7
Cluster-autoscaler image version: v1.0.3

While autoscaling, cluster-autoscaler generates the following error

```
$ kubectl -n kube-system logs cluster-autoscaler-7458cd4887-gzlvh
.......
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x2805da6]
goroutine 83 [running]:
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc420b75b90, 0xed28dac2e, 0xe331d0368, 0x518f0a0, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:99 +0x256
main.run(0xc420717bd0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:262 +0x46f
main.main.func2(0xc420010720)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:344 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:145 +0x97
bash-4.3# kubectl -n kube-system logs cluster-autoscaler-7458cd4887-gzlvh
```

**Comment by feiskyer** [comment]
Hi, @dhirenrouterabbit AKS support is not included in any autoscaler releases yet.  #861 is aiming to include it in v1.2.2.

**Comment by feiskyer** [comment]
However, build from master works now, e.g.

```
cd cluster-autoscaler
REGISTRY=<your-registry> make dev-release
```

**Comment by feiskyer** [comment]
> For which Kuberentes version builds from master works?

1.10+. It should also work for v1.9.X, but it's not recommended because autoscaler vendors kube-scheduler while there may be some conflicts with new versioned kube-scheduler.

**Comment by feiskyer** [comment]
@dhirenrouterabbit AKS support now included in https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.2.2. You run it with Kubernetes v1.10.X.

/close

**Comment by dhirenrouterabbit** [comment]
Thanks for the update but Azure is yet to launch 1.10.X version on AKS. I might have to wait.

**Comment by feiskyer** [comment]
exactly, AKS will launch 1.10 soon

**Comment by omerlh** [comment]
I just deployed AKS today, Kubernetes version is 1.10.5 and autoscaler version is `v1.3.1`. I just encountered the same error as above:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa056e4]

goroutine 52 [running]:
k8s.io/autoscaler/cluster-autoscaler/utils/errors.ToAutoscalerError(0x3844c0a, 0x12, 0x0, 0x0, 0x5cb0b40, 0xc421ec9a00)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/utils/errors/errors.go:74 +0x74
k8s.io/autoscaler/cluster-autoscaler/core.calculateScaleUpCoresMemoryTotal(0xc421ec9a10, 0x1, 0x1, 0xc42116e870, 0xc421eec720, 0x3, 0x4, 0xc420b47400, 0xc42114ab48, 0x7ff152b1f000, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:119 +0x1a4
k8s.io/autoscaler/cluster-autoscaler/core.computeScaleUpResourcesLeftLimits(0xc421ec9a10, 0x1, 0x1, 0xc42116e870, 0xc421eec720, 0x3, 0x4, 0xc420035f00, 0x0, 0x0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:56 +0x8e
k8s.io/autoscaler/cluster-autoscaler/core.ScaleUp(0xc421c05340, 0xc4206fc000, 0xc421c42500, 0xc421eec600, 0x4, 0x4, 0xc421ddac60, 0x3, 0x4, 0xc421eec6e0, ...)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:273 +0x57a
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc421c0d900, 0xbecd3685e7a18195, 0x32d73caa2, 0x5c8df20, 0x0, 0x0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:278 +0x1d86
main.run(0xc4207150e0)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:288 +0x48d
main.main.func2(0xc42005b800)
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:369 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:155 +0x92
```

**Comment by feiskyer** [comment]
@omerlh This is another potential issues caused CA panic. Let me file a PR to fix that

**Comment by feiskyer** [comment]
Created #1076 to fix the issue

**Comment by omerlh** [comment]
Great, thank you for the quick response. Do you want me to test it? How can I get it?

**Comment by feiskyer** [comment]
@omerlh Yep if you could also validate it. I have pushed the changed image to `feisky/cluster-autoscaler:1076`

**Comment by omerlh** [comment]
yep, look like the issue was resolved - now there is something with my configuration. Thanks!

**Comment by feiskyer** [comment]
@omerlh Thanks for validation
